<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource Item or media
 * @var array $derivatives
 * @var string $heading
 * @var string $class
 * @var bool $warn
 *
 * And passed options to helper Derivatives.
 */

if (!$derivatives) return;

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$labels = [
    'zip' => 'Zip of all files', // @translate
    'zipm' => 'Zip of media files', // @translate
    'zipo' => 'Zip of other files', // @translate
    'pdf' => 'Pdf', // @translate
    'txt' => 'Text', // @translate
    'text' => 'Extracted text', // @translate
    'alto' => 'Ocr Xml Alto', // @translate
    'iiif-2' => 'Iiif manifest v2', // @translate
    'iiif-3' => 'Iiif manifest v3', // @translate
    'pdf2xml' => 'Text from pdf as xml', // @translate
];

$escapeAttrs = function($key, $value) use ($escapeAttr): string {
    return $key . '="' . $escapeAttr($value) . '"';
};

$textsAttrs = '';
if ($warn) {
    $texts = [
        'data-text-warn' => $translate('Are you sure to download this file?'),
        'data-text-warn-size' => $translate('Are you sure to download the file of {size}?'),
        'data-text-no' => $translate('No'),
        'data-text-yes' => $translate('Yes'),
        'data-text-ok' => $translate('Ok'),
        'data-text-queued' => $translate('The file is in queue. Reload the page later.'),
        'data-text-units' => $translate('["Bytes", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB"]'),
    ];
    $textsAttrs = implode(' ', array_map($escapeAttrs, array_keys($texts), $texts));

    $this->headLink()->prependStylesheet($assetUrl('css/derivative-media.css', 'DerivativeMedia'));
    $this->headScript()->appendFile($assetUrl('js/derivative-media.js', 'DerivativeMedia'), 'text/javascript', ['defer' => 'defer']);
}

$resourceId = $resource->id();
$isMedia = $resource->getControllerName() === 'media';
?>

<div class="derivative-medias <?= empty($class) ? '' : ' ' . $escapeAttr($class) ?>">
    <?php if ($heading): ?>
    <h4><?= $escape($heading) ?></h4>
    <?php endif; ?>
    <aside class="derivative-list value" <?= $textsAttrs ?>>
        <ul class="derivatives">
            <?php foreach ($derivatives as $type => $derivative): ?>
            <?php if (!empty($derivative['feasible'])): ?>
            <?php if ($warn) {
                $attrs = [
                    'href' => '#',
                    'data-url' => $derivative['url'],
                    'data-size' => $derivative['size'],
                    'class' => 'derivative-media' . ($derivative['ready'] || $derivative['mode'] === 'live' ? '' : ' on-demand'),
                    'download' => $resourceId . '.' . $derivative['extension'],
                ];
            } else {
                $attrs = [
                    'href' => $derivative['url'],
                    'class' => 'derivative-media',
                ];
            }
            ?>
            <li class="derivative-<?= $type ?>">
                <a <?= implode(' ', array_map($escapeAttrs, array_keys($attrs), $attrs)) ?>>
                    <?= $isMedia ? $derivative['extension'] : $translate($labels[$type]) ?>
                </a>
            </li>
            <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </aside>
</div>
