<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 */

// Display the list of derivatives for the specified resource.

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$derivatives = $plugins->get('derivatives');
?>

<?= $derivatives($resource, [
    'heading' => $translate('Derivative files'), // @translate
    'class' => 'block resource-block block-derivative-media',
]) ?>
